### ISSUE TITLE
EDA and map downloads broken by values containing newlines

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/EdaLoadingIssues#91]
e.g. the vectorbase megastudy, export all the Study columns - see extra newlines in tab delimited file, e.g. `2016-Kawada-VGSC-Ae.aeypti`

Values containing tabs might break the download files too.

We have to expect values containing tab and newline.

Solution: adhere to the CSV quoting standard (works for tab delimited too) - use a CSV library in the exporter?

h/t @d-callan for spotting

**Comment by bobular** [comment]
Also breaks subsetting/merging/visualizations that use `Study name` as a variable see https://epvb.slack.com/archives/GBDR4LDNC/p1730843613123609 

It's really a data loading/patching issue (and remember to regenerate binary files afterwards if we fix it in-database).

Two options to fix:
1. remove the problem newlines in the ISA-Tab files (unless they are in the study characteristics yaml?) and reload the problem studies and regenerate the megastudy
2. hack a fix directly in the database


 (1) would be no big deal if we were already doing a release/rebuild
 (2) requires north/south sync as well as updating eda-inc

Neither are great!

**Comment by bobular** [comment]
Where should we move this ticket to?

**Comment by aurreco-uga** [comment]
and easy way to reproduce in vectorbase map is to select the variable "study name"as marker variable. 
```
2024-11-08 12:07:42.274 [rid:     ][jid:][p:][tid:227] ERROR ErrorMapper:69 - Caught Exception: 
 java.lang.RuntimeException: Expected 6 columns but parsed 1 in line:
in a gold mining town in Ghana and implications for
	at org.gusdb.fgputil.DelimitedDataParser.parseLineToArray(DelimitedDataParser.java:47) ~[service.jar:3.0.0]
	at org.veupathdb.service.eda.data.plugin.standalonemap.markers.MapMarkerRowProcessor.process(MapMarkerRowProcessor.java:36) ~[service.jar:3.0.0]
	at org.veupathdb.service.eda.data.plugin.standalonemap.StandaloneMapMarkersPlugin.writeResults(StandaloneMapMarkersPlugin.java:132) ~[service.jar:3.0.0]
```

There are 12 dataset display names including a newline: 

```
select count(*) from apidbtuning.datasetpresenter where display_name like '%'||CHR(10)||'%';
	12
```

or 15?
```
select count(*) from eda.ATTRIBUTES_VBP_MEGA_STUDY  where  OBI_0001622 like '%'||CHR(10)||'%'
15
```

 i would patch the databases (and regenerate files?), (the values in the study_name variable) .. we could test first in eda-inc..  
```
update  eda.ATTRIBUTES_VBP_MEGA_STUDY
set OBI_0001622 = REPLACE(OBI_0001622, CHR(10), ' ');
where OBI_0001622 like '%'||CHR(10)||'%'
```
and regenerate the file....

OR  maybe better is to check in StandaloneMapMarkersPlugin.java:132) if we could deal better with newlines.. until we can reload 

Definitely:    fix the original file for when we reload this if ever... the dataset presenters.xml too?
